cc_library(
    name = "base_application",
    visibility = ["//visibility:public"],

    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),

    deps = [
        "//platform:platform",
        "//utility:utility",
        "//machine:machine",
    ],
    includes = ["."],
)