dist: focal
sudo: required

language: c++

env:
  - bazel_version=3.1.0

script:
  - |
    make && \
    bazel \
      --output_base=$HOME/.cache/bazel \
      build //:emunisce_linux \

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libwxgtk3.0-gtk3-dev libglew-dev
  - |
    sysctl kernel.unprivileged_userns_clone=1
    OS=linux
    URL="https://github.com/bazelbuild/bazel/releases/download/${bazel_version}/bazel-${bazel_version}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
