version: 0.0.{build}

branches:
  only:
  - master
  - /dev-.*/

install:
  - ps: (new-object net.webclient).DownloadFile('https://storage.googleapis.com/arkhaix-emunisce/wxWidgets-3.0.3-binariesonly.zip', 'C:\wxwidgets.zip')
  - ps: Expand-Archive "C:\wxwidgets.zip" -DestinationPath "C:\wxWidgets-3.0.3" -Force
  - cinst bazel

configuration:
- Win32 Debug
- Win32 Release
- wx Debug
- wx Release
- Bazel Win32 Debug
- Bazel Win32 Release
- Bazel wx Debug
- Bazel wx Release

platform: x64

build:
  project: Emunisce.sln
  parallel: true
  verbosity: minimal