version: 0.0.{build}

branches:
  only:
  - master
  - /dev-.*/

install:
  - cinst bazel

configuration:
- Win32 Debug
#- Win32 Release
- wx Debug
#- wx Release
#- Bazel Win32 Debug
#- Bazel Win32 Release
#- Bazel wx Debug
#- Bazel wx Release

platform: x64

build:
  project: Emunisce.sln
  parallel: true
  verbosity: minimal