cc_library(
    name = "gameboy",
    visibility = ["//visibility:public"],

    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),

    deps = [
        "//machine:machine_interfaces",
        "//platform:platform",
        "//Utility:utility",
    ],
    includes = ["."],
)

# cc_library(
#     name = "cpu",
#     visibility = ["//visibility:public"],

#     srcs = [
#         "Cpu.cpp",
#         "CpuExec.cpp",
#     ],
#     hdrs = [
#         "Cpu.h",
#     ],
# )

# cc_library(
#     name = "display",
#     visibility = ["//visibility:public"],

#     srcs = [
#         "Display.cpp",
#     ],
#     hdrs = [
#         "Display.h",
#     ],
# )

# cc_library(
#     name = "input",
#     visibility = ["//visibility:public"],

#     srcs = [
#         "Input.cpp",
#     ],
#     hdrs = [
#         "Input.h",
#     ],
# )

# cc_library(
#     name = "memory",
#     visibility = ["//visibility:public"],

#     srcs = [
#         "Memory.cpp",
#         "RomOnly.cpp",
#         "Mbc1.cpp",
#         "Mbc3.cpp",
#         "Mbc5.cpp",
#     ],
#     hdrs = [
#         "Memory.h",
#         "RomOnly.h",
#         "Mbc1.h",
#         "Mbc3.h",
#         "Mbc5.h",
#     ],
# )

# cc_library(
#     name = "sound",
#     visibility = ["//visibility:public"],

#     srcs = [
#         "ChannelController.cpp",
#         "DutyUnit.cpp",
#         "EnvelopeUnit.cpp",
#         "LengthUnit.cpp",
#         "Sound.cpp",
#         "Sound1.cpp",
#         "Sound2.cpp",
#         "Sound3.cpp",
#         "Sound4.cpp",
#         "SoundGenerator.cpp",
#     ],
#     hdrs = [
#         "ChannelController.h",
#         "DutyUnit.h",
#         "EnvelopeUnit.h",
#         "LengthUnit.h",
#         "Sound.h",
#         "Sound1.h",
#         "Sound2.h",
#         "Sound3.h",
#         "Sound4.h",
#         "SoundGenerator.h",
#     ],
# )
