cc_library(
    name = "platform",
    visibility = ["//visibility:public"],

    hdrs = glob(["*.h"]),

    #deps = ["//LinuxPlatform:linux_platform"],
    deps = ["//WindowsPlatform:windows_platform"],
    includes = ["."],
)