cc_library(
    name = "base_application",
    visibility = ["//visibility:public"],

    deps = [
        "//BaseApplication/BaseApplication:base_application",
        "//BaseApplication/OpenGLRenderer:opengl_renderer",
    ],
    includes = ["."],
)