cc_library(
    name = "opengl_renderer",
    visibility = ["//visibility:public"],

    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),

    deps = [
        "//Platform:platform",
        "//Machine:machine",

        "//:gl",
    ],
    includes = ["."],
)
