cc_library(
    name = "utility",
    visibility = ["//visibility:public"],

    deps = [
        "//Utility/HqNx:hqnx",
        "//Utility/Serialization:serialization",
    ],
    includes = ["."],
)