cc_library(
    name = "hqnx",
    visibility = ["//visibility:public"],

    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),

    deps = [
        "//platform:platform",
        "//machine:machine_interfaces",
    ],
)
