cc_library(
    name = "base_application",
    visibility = ["//visibility:public"],

    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),

    deps = [
        "//Platform:platform",
        "//Utility:utility",
        "//Machine:machine",
    ],
    includes = ["."],
)